version: "3"
networks:
  backend:
services: 
  db:
    image: "mongo:latest"
    ports:
      - 27017:27017
    networks: 
    - backend
  cache:
    image: redis:alpine
    ports: 
      - 6379:6379
    networks: 
      - backend
  celery:
    build: .
    command: celery worker -A tasks -l info
    volumes:
      - .:/raven
    environment: 
      - REDIS=redis://cache
    depends_on:
      - db
      - cache
    networks:
      - backend
  backend: 
    build: 
      context: .
    depends_on:
      - db
      - cache
    environment:
      - DB=mongodb://db
      - REDIS=redis://cache
      - ENV=dev
    volumes:
      - .:/raven
    ports: 
      - 3001:3001
    networks:
      - backend
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes: 
      - ./client:/client
    depends_on: 
      - backend
