version: "3"
networks:
  backend:
services: 
  db:
    image: "mongo:latest"
    ports:
      - 27017:27017
    networks: 
    - backend
  cache:
    image: redis:alpine
    networks: 
    - backend
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    environment:
      - DB=mongodb://db
      - REDIS=redis://cache
      - ENV=dev
    ports: 
      - "3001:3001"
    env_file:
      - ./.env
    networks:
      - backend
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - backend
