version: "3"
services:
  db:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
  celery:
    build: .
    command: bash -c "make start-celery-beat & sleep 1 && make start-celery-watch"
    volumes:
      - .:/raven
    environment:
      - REDIS=redis://cache
      - DB=mongodb://db
    depends_on:
      - db
      - cache
  backend:
    build:
      context: .
    depends_on:
      - db
      - cache
    env_file: .env
    environment:
      - DB=mongodb://db
      - REDIS=redis://cache
      - ENV=dev
    volumes:
      - .:/raven
    ports:
      - 3001:3001
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - ./client/node_modules
    depends_on:
      - backend
