version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: sudo make init
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
