name: CI Workflow
on: [push, pull_request]
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup Node 11.x
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd client && npm ci

      - name: Run tests
        run: |
          make test-app
